### ISSUE TITLE
can't reimplement the final result

### ISSUE THREAD

**Issue by bobwan1995** [qinzzz/Multimodal-Alignment-Framework#1]
Hi, thanks for your awesome work. Now I want to use your codes, but I can't get the same result as your paper said. I can only get 56.04 with avg(l_m+f_m), while the paper is 59.51. Furthermore, I can only get 58.26 with the final model, while the paper is 61.43. I've used the weight you put on google drive, the result is only 30.55. I'm wondering how to get the result as your paper mentioned. Thank you so much!

**Comment by qinzzz** [comment]
Hi, I'm sorry for that. I suppose this is because of the difference in visual features. May you download the features & detected dicts for test in the readme and try again?

**Comment by bobwan1995** [comment]
Thank you so much for your reply! I will have a try.
________________________________
