### ISSUE TITLE
Question about unsupervised setting

### ISSUE THREAD

**Issue by cws7777** [qinzzz/Multimodal-Alignment-Framework#3]
First of all, thank you for the great work! I really enjoyed reading your paper! :)

I have a question about unsupervised setting.

Does this public branch have a code block of unsupervised setting? I couldn't find the part in any file of the repository..
(Might be somewhere but I couldn't)
Or is that the line 23 ~ 25 in `train_model.py`?

I saw the unsupervised argument in `arg.parse` as `#TODO` from `main.py`, and guessed that "The authors didn't implement yet in this repository..?"

Thanks! :)
Hope you have a good one!

**Comment by cws7777** [comment]
In addition, the result of evaluating in the Readme which is `python test.py ` should be 61.43%, shouldn't be?
However, I get 61.37%.. :'( I followed up everything that is in the Readme..

**Comment by qinzzz** [comment]
Sorry that I didn't provide code for the unsupervised setting yet in this repo, but the evaluation before training (line 23 ~ 25 in train_model.py) may provide a similar result. 
About the model result, the reported result takes the mean of several runs, and I just saved one checkpoint of them.
